
name: Test Manual Action

on:
  workflow_dispatch:
          
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Print to Console
        run: |
            echo "Hello World!"
